server:
  port:8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flashcard_system_database?createDatabaseIfNotExist=true
    username : root
    password: 200168200526

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
